last_change = 2026-09-23T12:24:20.019115Z
addr = 0xcb0390
size = 0x1
name = "IGameSystem_OnClientPostAdvanceTick"

[header]
name = "IGameSystem_OnClientPostAdvanceTick"
addr = 0xcb0390

[header.args]
